#!/bin/zsh

alias ll='ls -la' # -lahGt
alias g='git'
alias go='git checkout '
alias gb='git branch'
alias gup='git up'
alias gpp='git up && git push'
alias gp='git push'
alias gpa='git push --all'
alias grm='git rm $(git ls-files --deleted)'
alias gs='git status -sb'
alias gst='git status -sb'
alias gl='git lg -n 10'
alias glg='git lg'
alias gd='git diff -b'
alias gdc='git diff --cached'
alias gap='git add -p'
alias gm='git merge'

alias vi='vim -u NONE -N' # plain vim with no vimrc, but not vi compatible
alias tm='tmux -u attach || tmux -u new'
alias less='less -R '
alias ..='cd ..'
alias :q='exit'
alias ttr='touch tmp/restart.txt'
alias tailx='tail -f /opt/nginx/logs/access.log'
alias rec_pull_bash='for i in `ls`; do cd $i; git pull; cd ..; done'
function grp() { grep -rn --exclude=\*.swp --exclude=\*.log --exclude=tags --exclude=gems.tags --exclude-dir=.git --exclude-dir=tmp $1 . 2>/dev/null }
function greps() { grep -rn --exclude=\*.swp --exclude=\*.log --exclude=tags --exclude=gems.tags --exclude-dir=.git --exclude-dir=tmp $1 . 2>/dev/null | sed -E 's/[[:space:]]+//' | grep $1 }
alias rspec_cov='RUN_COVERAGE=true rspec spec'
alias gi='gem install'
alias prod='production'
alias pow='powder'
alias start_memcached='/usr/local/opt/memcached/bin/memcached'
alias largefiles='find . -ls | sort -n -k 7 | tail -n 20'
alias pt='heroku addons:open papertrail'
alias bd='bundle'
alias bi='bundle install'
alias bu='bundle update'
alias bo='bundle outdated'
alias be='bundle exec'
alias b2d='boot2docker'
alias cn='cd ~/Dropbox/Notes'
alias cpd='cap production deploy'

# OS X
alias showhidden='defaults write com.apple.finder AppleShowAllFiles YES'
alias hidehidden='defaults write com.apple.finder AppleShowAllFiles NO'
alias rmdsstores="find . -name '*.DS_Store' -type f -delete"
alias bs='brew services'
alias bc='brew cask'
alias brewout="brew update && echo \"$fg[blue]==>$reset_color\" && brew outdated"
alias brewup="brew upgrade && brew cleanup"

# Fun
alias fact="elinks -dump randomfunfacts.com | sed -n '/^| /p' | tr -d \|"
alias drumroll='afplay ~/Dropbox/Resources/Sounds/drumroll.mp3'
alias drumrollplease='curl -Ls http://bit.ly/drumrollplease | bash'

# dw specific
alias daw='cd ~/code/dawanda_main'
alias lo='loveos-cli'
alias cl='cd ~/code/loveos'

# Other
trash () {
  local trash_dir="${HOME}/.Trash"
  local temp_ifs=$IFS
  IFS=$'\n'
  for item in "$@"
  do
    if [[ -e "$item" ]]
    then
      item_name="$(basename $item)"
      if [[ -e "${trash_dir}/${item_name}" ]]
      then
        mv -f "$item" "${trash_dir}/${item_name} $(date "+%H-%M-%S")"
      else
        mv -f "$item" "${trash_dir}/"
      fi
    fi
  done
  IFS=$temp_ifs
}

rspec() {
  if [ -f Gemfile ]; then
    bundle exec rspec $@
  else
    rspec $@
  fi
}
