#!/bin/zsh

function mcdir() {
  mkdir -p $1
  cd $1
}

function name() {
  dir=$2
  [[ -d $dir ]] || dir=.
  find $dir -name "*$1*"
}

function tn() {
  terminal-notifier -message "$1"
}

# Returns whether the given command is executable or aliased.
_has() {
  return $( whence $1 >/dev/null )
}
