#!/bin/zsh

###################
# Vi mode indicator
function zle-line-init zle-keymap-select {
  VIM_PROMPT="%{$fg_bold[yellow]%}[% NORMAL]% %{$reset_color%}"
  RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}"
  zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select
###################

autoload -U colors && colors
setopt promptsubst

git_br() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || ref=$(git rev-parse --short HEAD 2> /dev/null) || return
  if [[ -n $(git status -s 2> /dev/null) ]]
  then
    echo "%{$fg[magenta]%}${ref#refs/heads/}%{$reset_color%} "
  else
    echo "%{$fg[green]%}${ref#refs/heads/}%{$reset_color%} "
  fi
}

hn=$(scutil --get ComputerName | tr '[:upper:]' '[:lower:]' | sed 's/ts //g')
local host='%{$fg[yellow]%}${hn}%{$reset_color%}'
local gitbr='$(git_br)'
local final_char='%%'
local pwd='%{$fg[green]%}%c%{$reset_color%}'
local last_cmd_status='%(?.%{$fg[green]%}.%{$fg[red]%})$final_char%{$reset_color%}'

PROMPT="${host}:${pwd} ${gitbr}${last_cmd_status} "
