#!/bin/zsh

###################
# Vi mode indicator
function zle-line-init zle-keymap-select {
  VIM_PROMPT="%{$fg_bold[yellow]%}[% NORMAL]% %{$reset_color%}"
  RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}"
  zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select
###################

autoload -U colors && colors
setopt promptsubst

git_br() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || ref=$(git rev-parse --short HEAD 2> /dev/null) || return
  if [[ -n $(git status -s 2> /dev/null) ]]
  then
    echo "%{$fg[magenta]%}${ref#refs/heads/}%{$reset_color%} "
  else
    echo "%{$fg[green]%}${ref#refs/heads/}%{$reset_color%} "
  fi
}

# local default_emoji='🐨'
# local emoji=${PROMPT_EMOJI:-$default_emoji}

# local user='%{$fg[green]%}%n%{$reset_color%}'
local username=$USER[0,5]
local user='%{$fg[green]%}${username}%{$reset_color%}'
# local host='%{$fg[green]%}%m%{$reset_color%}'
hn=$(hostname)
# hn=$(scutil --get ComputerName | tr '[:upper:]' '[:lower:]')
local hostname=$hn[0,3]
# local host='%{$fg[green]%}${hostname}%{$reset_color%}'
local gitbr='$(git_br)'

if [[ "${hn:(-5):5}" == 'local' || "${hn:(-3)}" == 'lan' || "${hn:(-5)}" == 'mynet' || "${hn:(-11)}" == 'localdomain' ]]; then
  local pwd='%{$fg[blue]%}%c%{$reset_color%}'
  local last_cmd_status='%(?.%{$fg[blue]%}.%{$fg[red]%})○%{$reset_color%}'
else
  local pwd='%{$fg[green]%}%c%{$reset_color%}'
  local last_cmd_status='%(?.%{$fg[green]%}.%{$fg[red]%})○%{$reset_color%}'
fi

# # With current time
# PROMPT="${pwd} ${gitbr}%{$fg[blue]%}%*%{$reset_color%} ${last_cmd_status} "

# PROMPT="${emoji} ${pwd} ${gitbr}${last_cmd_status} "
PROMPT="${pwd} ${gitbr}${last_cmd_status} "
