#!/bin/zsh

if [ ! -d ~/dotfiles ]; then
  echo 'This script excpects dotfiles to be cloned in the home dir'
  exit 1
fi

# -------------------------------------------------------------------
# Symlink dotfiles

dots=(
  agignore
  aliases
  bin
  completions
  functions
  fzfrc
  gemrc
  gitattributes
  gitconfig
  githelpers
  gitignore_global
  gitmessage
  inputrc
  prompt
  pryrc
  rspec
  tmux.conf
  vim
  vimrc
  zsh
  zshrc
)

for dot in "${dots[@]}"
do
  ln -sf "$HOME/dotfiles/$dot" "$HOME/.$dot"
done

touch ~/.private_aliases
touch ~/.private_profile
touch ~/.tmux_private.conf

if [ $SPIN ]; then
  git config --global user.email "tadas.scerbinskas@shopify.com"
  git config --global user.signingkey 15039BD59A5E6A5E48040923F95286C21AB66AF8
  git config --global commit.gpgsign true
fi

# -------------------------------------------------------------------
# Install some packages

packages=(
  ctags
  fzf
  silversearcher-ag
)

if command -v apt-get &> /dev/null; then
  for pkg in "${packages[@]}"
  do
    # yep, this won't actually work when package name differs from the
    # executable (like ag) but oh well
    if ! command -v $pkg &> /dev/null; then
      sudo apt-get install -y $pkg
    fi
  done
fi


# -------------------------------------------------------------------

# Vim
[[ -x /usr/bin/vim.basic ]] && alias vim=/usr/bin/vim.basic

# Vim Undo
mkdir -p ~/.vim/undo

# Vim Plugins
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim -es -u vimrc -i NONE -c "PlugInstall" -c "qa"

# Tmux Plugin Manager
if [ ! -d ~/.tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
