#!/usr/bin/env bash

# Open git repo in Browser
ob() {
    if [ -d .git ]; then
        url=$(git remote -v | grep push | awk '{ print $2 }' | sed 's/\.git//')

        if [[ $url =~ ^https?: ]]; then
            open "$url"
        else
            if [[ $url =~ ^git@ ]]; then
                url=$(echo "$url" | sed 's#:#/#' | sed 's#git@#https://#')
                open "$url"
            else
                echo "Remote URL not supported: $url"
                return 1
            fi
        fi
    else
        echo "This doesn't seem to be a git repo"
        return 1
    fi
}
