#!/bin/zsh

# Given a long-running process in the terminal:
#
# - Ctrl+Z to suspend it
# - Run `push-when-done`
# - Output resumes, when done will show a notification

function push-when-done() {
  last_command=$(history | tail -1 | cut -d' ' -f3-)

  fg && echo "✔︎ $last_command" | pushover
}
