#!/bin/zsh

# Given a long-running process in the terminal:
#
# - Ctrl+Z to suspend it
# - Run `tell-me-when-done`
# - Output resumes, when done will show a notification

function tell-me-when-done() {
  last_command=$(history | tail -1 | cut -d' ' -f3-)

  fg && osascript -e "display notification \"$last_command\" with title \"Done\""
}
